# Google Cloud Build configuration for deploying to Cloud Run

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/fitos-ai-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/fitos-ai-backend:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/fitos-ai-backend:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/fitos-ai-backend:latest'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'fitos-ai-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/fitos-ai-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'ENVIRONMENT=production'
      - '--max-instances'
      - '10'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '60s'

images:
  - 'gcr.io/$PROJECT_ID/fitos-ai-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/fitos-ai-backend:latest'

options:
  machineType: 'N1_HIGHCPU_8'
