"""AI Coach endpoints - multi-agent coaching conversations"""

from fastapi import APIRouter, HTTPException, Depends, Request
from pydantic import BaseModel
from typing import List, Dict, Any
import logging

from app.agents import build_coach_graph, ChatMessage, UserContext, ChatAction
from app.core.auth import get_current_user_id
from app.core.rate_limit import limiter

logger = logging.getLogger("fitos-ai")
router = APIRouter()

# Build graph once at startup
coach_graph = build_coach_graph()


class ChatRequest(BaseModel):
    """Chat request payload"""
    message: str
    conversationHistory: List[ChatMessage] = []
    userContext: UserContext


class ChatResponse(BaseModel):
    """Chat response payload"""
    message: str
    agentSource: str
    actions: List[ChatAction] | None = None
    shouldEscalate: bool = False


@router.post("/chat", response_model=ChatResponse)
@limiter.limit("60/minute")
async def chat(
    request: Request,
    body: ChatRequest,
    user_id: str = Depends(get_current_user_id),
):
    """
    Multi-agent coaching conversation endpoint.

    Requires a valid Supabase JWT in the Authorization header.
    The user_id is extracted server-side from the token — the client-provided
    userContext.user_id is overwritten with the JWT-verified value.

    Rate limit: 60 requests/minute per user.
    """
    try:
        # Override client-provided user_id with JWT-verified value
        body.userContext.user_id = user_id

        logger.info(f"Processing chat for user {user_id}: {body.message[:50]}...")

        # Prepare state
        initial_state = {
            "message": body.message,
            "user_context": body.userContext,
            "conversation_history": body.conversationHistory,
            "current_agent": None,
            "should_escalate": False,
            "response": None,
            "agent_source": None,
            "suggested_actions": [],
            "confidence": 0.0,
            "complexity": "moderate",
            "iterations": 0,
        }

        # Run through agent graph
        result = await coach_graph.ainvoke(initial_state)

        # Build response
        response = ChatResponse(
            message=result["response"] or "I'm having trouble processing that. Could you rephrase?",
            agentSource=result["agent_source"] or "general",
            actions=result.get("suggested_actions"),
            shouldEscalate=result.get("should_escalate", False)
        )

        logger.info(f"Response generated by {response.agentSource} agent")

        return response

    except Exception as e:
        logger.error(f"Error in chat endpoint: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail="Failed to process chat message")


@router.post("/action")
async def execute_action(
    request: Request,
    action: ChatAction,
    user_id: str = Depends(get_current_user_id),
):
    """
    Execute a suggested action from the AI coach.

    Actions include:
    - log_workout: Redirect user to workout logging
    - adjust_program: Modify training program
    - set_reminder: Create a notification
    - escalate_trainer: Notify trainer
    """
    try:
        logger.info(f"Executing action: {action.type}")

        # In a real implementation, this would:
        # 1. Validate the action
        # 2. Make changes to database
        # 3. Send notifications
        # 4. Return success/failure

        # For now, just acknowledge
        return {
            "success": True,
            "action": action.type,
            "message": f"Action {action.type} executed successfully"
        }

    except Exception as e:
        logger.error(f"Error executing action: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail="Failed to execute action")
